/**
 * If you are not familiar with React Navigation, check out the "Fundamentals" guide:
 * https://reactnavigation.org/docs/getting-started
 *
 * Autogenerated by Expo
 */
import { createStackNavigator } from "@react-navigation/stack";
import * as React from "react";
import Drawer from "./Drawer";

export default function Navigation({ colorScheme }) {
  return <RootNavigator />;
}

// A root stack navigator is often used for displaying modals on top of all other content
// Read more here: https://reactnavigation.org/docs/modal
const Stack = createStackNavigator();

function RootNavigator() {
  return (
    <Stack.Navigator screenOptions={{ headerShown: false }}>
      <Stack.Screen name="Root" component={Drawer} />
    </Stack.Navigator>
  );
}
