/**
 * Autogenerated by Expo
 **/

import { Ionicons } from "@expo/vector-icons";
import * as Font from "expo-font";
import {
  useFonts,
  Inter_100Thin,
  Inter_200ExtraLight,
  Inter_300Light,
  Inter_400Regular,
  Inter_500Medium,
  Inter_600SemiBold,
  Inter_700Bold,
  Inter_800ExtraBold,
  Inter_900Black,
} from "@expo-google-fonts/inter";
import * as SplashScreen from "expo-splash-screen";
import * as React from "react";

export default function useCachedResources() {
  const [isLoadingComplete, setLoadingComplete] = React.useState(false);

  // Load any resources or data that we need prior to rendering the app
  React.useEffect(() => {
    async function loadResourcesAndDataAsync() {
      try {
        SplashScreen.preventAutoHideAsync();

        let [fontsLoaded] = Font.loadAsync({
          "Inter-Thin": Inter_100Thin,
          "Inter-ExtraLight": Inter_200ExtraLight,
          "Inter-Light": Inter_300Light,
          Inter: Inter_400Regular,
          "Inter-Medium": Inter_500Medium,
          "Inter-SemiBold": Inter_600SemiBold,
          "Inter-Bold": Inter_700Bold,
          "Inter-ExtraBold": Inter_800ExtraBold,
          "Inter-Black": Inter_900Black,
        });
      } catch (e) {
        // We might want to provide this error information to an error reporting service
        console.warn(e);
      } finally {
        setLoadingComplete(true);
        SplashScreen.hideAsync();
      }
    }

    loadResourcesAndDataAsync();
  }, []);

  return isLoadingComplete;
}
